title: "Vinícius Bôscoa"
subtitle: Eu crio softwares que ajudam a potencializar seus resultados.
description: >- # this means to ignore newlines until "baseurl:"
  "Eu crio softwares que ajudam a potencializar seus resultados."

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: Home
    url: /
  - text: Sobre
    url: /about
  # - text: Blog
  #   url: /blog
  # - text: Gallery
  #   url: /gallery
  # - text: Shop
  #   url: /shop
  # - text: Contact
  #   url: /contact
  # - text: Styleguide
  #   url: /styleguide
  # - text: Get Started
  #   url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpg
author: Vinícius Bôscoa
author_bio: >-
  <p>
    Sou desenvolvedor, apaixonado por tecnologia. Desenvolver é meu hobby e profissão.
    Sou capaz de navegar facilmente entre os mundos frontend e backend, 
    mas minha preferência é o backend.
  </p>
  <p>
    Gosto de desafios e resolver problemas dos mais variados tipos.
  </p>
author_email: "vinicius.boscoa@gmail.com"
author_location: Brazil
author_website_url: "https://viniboscoa.dev"
typewrite-text: Eu crio softwares que ajudam a potencializar seus resultados.

# Experiences
author_work_experiences:
  - company_name: Google
    company_logo: google.png
    company_url: https://google.com
    designation: Software Engineer
    description: Worked on various Google Products
    visibility: true
  - company_name: Microsoft
    company_logo: microsoft.png
    company_url: https://microsoft.com
    designation: Azure Developer
    description: Worked on various Azure Cloud Products
    visibility: true

# Education
author_education_details:
  - college_logo: mit.png
    college_name: MIT
    college_url: https://mit.org
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: true

# Projects
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in
    visibility: false
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://hack4r.com
    visibility: false

# social links
twitter_username: Virb30
github_username: virb30
# facebook_username: johndoe
linkedin_username: vinicius-boscoa
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username:

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0
show_newsletter_form: false

# formspree (contact form)
# formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
